### ISSUE TITLE
Sprint 4 - Hardening

### ISSUE THREAD

**Issue by LoreBWolf** [geetz-app/geetz-management#134]
# Sprint Tracking: [Sprint Name/Number] 🚀

**Sprint Duration:** [20/12/2024] - [27/12/2024]  
**Sprint Goal:** Refactor hot-code and minor bug fixes related to features implemented in the last 2 sprints

---

## 📌 Key Objectives
1. Add missing image cover field to collection refactor
2. Integrate collection refactor
3. Refactor publication enttity
4. Fix minor UI bugs in the mobile front
5. Clean up code in the mobile front
6. Adjust Story UI in the web front
7. Finish image publication creation
8. Finish new publication modal
---

## 🔍 Progress Overview
| Category         | Total Issues | Open Issues | Closed Issues | Progress (%) |
|-------------------|--------------|-------------|---------------|--------------|
| Web Frontend      |        6      |       3      |       3        |      50%        |
| Mobile Frontend   |       13       |        2     |      11         |        84,61%      |
| Backend           |       6       |        6     |        0       |        0%      |
| UI/UX             |       -       |       -      |       -        |        -      |

---

## 🖥️ Web Frontend
**Repository:** [Link to Web Frontend Repository](https://github.com/geetz-app/geetz-frontend) 

### Issues  
- [x] geetz-app/geetz-frontend#341 `reopenend`
- [ ] geetz-app/geetz-frontend#362
- [x] geetz-app/geetz-frontend#380
- [x] geetz-app/geetz-frontend#273 `reopenend`
- [ ] geetz-app/geetz-frontend#379 
- [x] geetz-app/geetz-frontend#365 `reopenend` 

**Key Notes:**  
- Frontend has several features very close to completion, we believe its in the best interest of the product to deliver the new collection refactor, image publication, story UI fixes and new publication modal in the next build (0.2.0). Victor will be working on both fronts during this spring.

---

## 📱 Mobile Frontend
**Repository:** [Link to Mobile Frontend Repository](https://github.com/geetz-app/geetz-frontend)  

### Issues  
- [x] geetz-app/geetz-mobile#224
- [ ] geetz-app/geetz-mobile#228
- [x] geetz-app/geetz-mobile#229
- [x] geetz-app/geetz-mobile#230
- [x] geetz-app/geetz-mobile#231
- [x] geetz-app/geetz-mobile#232
- [x] geetz-app/geetz-mobile#233
- [x] geetz-app/geetz-mobile#243
- [x] geetz-app/geetz-mobile#235
- [x] geetz-app/geetz-mobile#236
- [x] geetz-app/geetz-mobile#237
- [x] geetz-app/geetz-mobile#238
- [x] geetz-app/geetz-mobile#239

**Key Notes:**  
- To honor de spirit a hardening sprint, sprint must be focused on fixing existing code while still hot with minor bug or UI adjustments. With that in mind, mobile team requested an update on the board priority. Board ware reprioritized and the issues above ware selected by the team to fix during the hardening sprint.  All following issues come from the tracking issue geetz-app/geetz-management#115 .

---

## 🛠️ Backend
**Repository:** [Link to Backend Repository](https://github.com/geetz-app/geetz-backend)  

### Issues  
- [ ] geetz-app/geetz-backend#19 `reopenend` 
- [ ] geetz-app/geetz-backend#54
- [ ] geetz-app/geetz-backend#55
- [ ] geetz-app/geetz-backend#53
- [ ] geetz-app/geetz-backend#51
- [ ] geetz-app/geetz-backend#37

**Key Notes:**  
Team has requested a reopened of the issue geetz-app/geetz-backend#19 , the reason being that the current refactor was insufficient to be integrated in detriment of the lack of fields for cover image on the payload. Issue has been reopened and frontends have been put in high alert to integrate the feature as soon as the backend releases it.

Due to issues related to infrastructure and the high demand for Gabriel's skills in the mobile frontend, very little of the original planning ware able to be resolved during last sprint. This sprint comes with more humble goals considering its duration and the holidays in the following weeks. Gabriel has giving a estimative that he will only be able to drop mobile and focused on notification feature after Wednesday (25.12), due to the significant amount of code to be cleaned and reviewed in the mobile front.

---

## 🎨 UI/UX
**Repository:** [Link to UI/UX Repository]  

### Issues  
- [ ] #423  
- [ ] #424  

**Key Notes:**  
- [Insert relevant notes, blockers, or updates]

---

## 🔄 Retrospective Notes
- [Insert any lessons learned, blockers, or feedback for improvement]

---

## 🔗 Useful Links
- [Link to Sprint Board]
- [Link to Documentation]
- [Link to Meeting Notes]

---

**Comment by LoreBWolf** [comment]
> [!NOTE] 
> - [ ] geetz-app/geetz-mobile#248
>
> **Status:**  Added to the sprint
> **Reason:** _Issue was identified by Victor during the sprint while working on UI fixes_

**Comment by LoreBWolf** [comment]
> [!WARNING]
> **Status:** Reopened - Failed QA testing
> **Reviewer:** @LoreBWolf 
>
> - [ ] geetz-app/geetz-frontend#362
> - [ ] geetz-app/geetz-frontend#380
> - [ ] geetz-app/geetz-frontend#333
> - [ ] geetz-app/geetz-frontend#334
> - [ ] geetz-app/geetz-frontend#273
> - [ ] geetz-app/geetz-frontend#365

**Comment by LoreBWolf** [comment]
> [!IMPORTANT]
> 
> _Sprint extended until January 2 (thursday), sprint planning for sprint 5 schedule for January 3 at 1PM_

---

### Builds

`mobile v.0.4.0` on January 2

**Build is expected to contain:** All issues listed on the sprint log

`web v0.2.0` on January 2

**Build is expected to contain:** 1. New publication modal; 2. CM[^1], image upload; 3. CM, adaptive cropper; 4. CM, color correction sliders; 5. CM, Dynamic caption; 6. CM, Carrousels; 7. S[^2], story cards; 8. S, Story navigation; S,  Progress bar navigation; 9. S, Likes; 10. S, Visualizations; 11. Chat fixes; 12. Comments fixes.

[^1]: Creation modal
[^2]: Stories

---

### Issues added to the sprint

- [ ] geetz-app/geetz-mobile#243
- [ ] geetz-app/geetz-frontend#392
