### ISSUE TITLE
Ajustes do feed Web v.1.0.1

### ISSUE THREAD

**Issue by LoreBWolf** [geetz-app/geetz-management#45]
- [x] geetz-app/geetz-frontend#321
- [x] geetz-app/geetz-frontend#322
- [x] geetz-app/geetz-frontend#323
- [x] geetz-app/geetz-frontend#324
- [x] geetz-app/geetz-frontend#327
- [x] geetz-app/geetz-frontend#328
- [x] geetz-app/geetz-frontend#331
