### ISSUE TITLE
Visualização de stories

### ISSUE THREAD

**Issue by LoreBWolf** [geetz-app/geetz-management#58]
**🔗 Relates to**

geetz-app/geetz-management#68

**💬 Description**

"Como usuário eu quero poder saber quem visualizou meu story"

"Como usuário eu quero poder saber quem curtiu meu story"

Precisamos desenvolver uma maneira de indicar para o usuário quem visualizou e/ou curtiu seu story. Telas de visualização e curtida ja foram produzidas pela Luiza (Designer) e podem ser encontradas no figma dentro da sessão de story. Lista de visualização deve ser ordenada por ordem de cronológica de visualização mais recente.  Curtidas não impactam o ordenamento da lista de visualização, mas são indicados ao lado de quem visualizou.

O usuário pode acessar a feature dentro de seus próprios stories clicando sobre a visualização no canto inferior esquerdo do card. A feature também é acessível pela web ou app. Este componente sera referido como preview de visualizações, dentro dele sera exposto apenas as últimas 3 visualizações no formato do avatar de quem visualizou.

Clicar no preview de visualização leva o usuário para tela de listagem de visualização. Note que esta tela apesar de se parecer com um bottomsheet, não é. A tela permite rolagem vertical e ao clicar em um usuário da lista, o usuário deve ser levado ao perfil de quem clicou.

**✨ Issues**

- [x] geetz-app/geetz-frontend#338
- [x] geetz-app/geetz-mobile#157
- [x] geetz-app/geetz-backend#24
- [x] geetz-app/geetz-backend#25
- [x] geetz-app/geetz-frontend#339
- [x] geetz-app/geetz-mobile#158

**💻 Enviorment**

1. Geetch App
2. Geetch Frontend

**🧰 Resources**

![Image](https://github.com/user-attachments/assets/4fc426bb-2aab-4094-9322-bd530702e15a)
