### ISSUE TITLE
Story player

### ISSUE THREAD

**Issue by LoreBWolf** [geetz-app/geetz-management#65]
**🔗 Relates to**

- 

**💬 Description**

"Como usuário eu quero poder visualizar os stories de outros usuários"

Precisamos desenvolver o player de stories para que o usuário possa de fato visualizar um story. Um story é visualizado no momento que é renderizado/aberto, seria interessante para fins de metricas para criadores de conteúdo saber também tempo de visualização e se o story foi pulado ou visualizado até o fim, contudo uma visualização em si é contablizada mesmo que o usuário n veja o story até o final.

**O usuário possuí algumas opções de como interagir com os stories:**

1. O usuário pode curtir um story clicando no coração no canto inferior direito da tela
2. O usuário pode passar para o proximo story ou anterior clicando respectivamente na direita e esquerda do story
4. O usuário pode voltar para um story específico clicando na progress bar daquele story
6. O usuário pode pular para os stories do próximo usuário da lista

**Progress bar**

Caso o usuário possua multiplos stories a progress bar é dividida igualmente no espaço disponível. Todas progress bars compartilham o mesmo gradiente, e não uma interação do gradiente para cada progressbar.

**Player**

1. Storys dão autoplay quando renderizados, no mobile podem ser pausados com hold, na web com o botão de pausar.

2. Storys no mobile não possuem opção de serem mutados, na web podem ser mutados clicando no botão de mute, mutar um story faz com que todos os stories sequentes sejam mutados, contúdo ao entrar devolta na navegação desfaz o mute.

3. Na web, ON HOVER sobre stories do próximo usuário ou do anterior, removem o overlay que escuresse o story e dão play no vídeo mutado, a remover o mouse de cima do story vídeo é pausado, ao clicar no card usuário navega para o story do usuário que selecionou e video é reproduzido no ponto que parou.

**✨ Issues**

💻  Web

- [x] geetz-app/geetz-frontend#340
- [x] geetz-app/geetz-frontend#341
- [x] geetz-app/geetz-frontend#342
- [x] geetz-app/geetz-frontend#343
- [x] geetz-app/geetz-frontend#344
- [x] geetz-app/geetz-frontend#345

📱 Mobile

- [x] geetz-app/geetz-mobile#160
- [x] geetz-app/geetz-mobile#161
- [x] geetz-app/geetz-mobile#162
- [x] geetz-app/geetz-mobile#163
- [x] geetz-app/geetz-mobile#159

**💻 Enviorment**

1. Geetch App
2. Geetch Frontend

**🧰 Resources**
