### ISSUE TITLE
Sprint 3 - Stories. Feed Mobile, Notifications and New web Publication

### ISSUE THREAD

**Issue by LoreBWolf** [geetz-app/geetz-management#85]
**🏃‍♂️ Sprint overview**

Start Date [ 06/12/2024 ]

End Date [ 20/12/2024 ]

A presente sprint tem como objetivo finalizar e testar a implementação inicial da criação de stories (image only), assim como a implementação da feature de notificações no backend, com o objetivo de pavimentar o desenvolvimento para acelerar o frontend. 

Durante esta sprint teremos uma configuração diferente de time, o desenvolvedor jr. Victor sera realocado para o mobile a fim de acelerar o seu desenvolvimento. Temos uma previsão de 2 builds para o mobile e 1 build do web para esta sprint. 

- A primeria build mobile possui previsão para a noite de segunda feira (9/12) - manhã de terça-feira (10/12), e inclui festures de criação e edição de stories de imagens, custom picker e ajustes de UI do feed.
- A segunda build mobile inclui a finalização de ajustes do feed e implementação do novo card de snipz responsivo, esta possuí previsão de release para o final de semana da primeira semana de sprint.
- A build web esta prevista para o final da sprint, contando com as features novas de criação de publicação estática

**🎯 Sprint Goals**

1. Develop video story creation feature
2. Develop basic video editing features for story creations
3. Fix QA reviewed image story creation features
4. Implement new snipz timeline card
5. Implement mobile feed adjustments
6. Develop new backend notification feature
7. Design new screens and user flows for notifications Web and Mobile
8. Develop new web publication feature
9. Develop adjustmet features for web publication
10. Develop cropper feature for web publication
11. Develop carousel feature for web publication

**Issues listed by repository**

Abaixo estão listatadas todas a issues produzidas com o objetivo de atingir a meta proposta para a presente sprint. As mesmas foram separadas por repositório para maior facilidade de identificação. Obs: no caso de mais issues serem adicionadas durante a sprint, esta ocorreram na forma de comentário para melhor documentação

**💾 Backend**

- [ ] geetz-app/geetz-backend#37
- [x] geetz-app/geetz-backend#50
- [ ] geetz-app/geetz-backend#19
- [ ] geetz-app/geetz-backend#51
- [x] geetz-app/geetz-backend#32
- [x] geetz-app/geetz-backend#33
- [ ] geetz-app/geetz-backend#52
- [ ] geetz-app/geetz-backend#53
- [ ] geetz-app/geetz-backend#54
- [ ] geetz-app/geetz-backend#55
- [ ] geetz-app/geetz-backend#56
- [ ] geetz-app/geetz-backend#57

**📱 App**

- [x] geetz-app/geetz-mobile#140
- [x] geetz-app/geetz-mobile#150
- [x] geetz-app/geetz-mobile#151
- [x] geetz-app/geetz-mobile#152
- [x] geetz-app/geetz-mobile#153
- [ ] geetz-app/geetz-mobile#154
- [ ] geetz-app/geetz-mobile#155
- [x] geetz-app/geetz-mobile#156
- [x] geetz-app/geetz-mobile#157
- [x] geetz-app/geetz-mobile#158
- [x] geetz-app/geetz-mobile#159
- [x] geetz-app/geetz-mobile#160
- [x] geetz-app/geetz-mobile#161
- [x] geetz-app/geetz-mobile#162
- [x] geetz-app/geetz-mobile#180

**💻 Web**

- [x] geetz-app/geetz-frontend#359
- [x] geetz-app/geetz-frontend#333
- [x] geetz-app/geetz-frontend#334
- [x] geetz-app/geetz-frontend#342
- [ ] geetz-app/geetz-frontend#362
- [x] geetz-app/geetz-frontend#363
- [x] geetz-app/geetz-frontend#365
- [x] geetz-app/geetz-frontend#364
- [x] geetz-app/geetz-frontend#366
- [x] geetz-app/geetz-frontend#367
- [x] geetz-app/geetz-frontend#368

**🎨 Design**

- [ ] #102
- [x] #103
- [x] #104
- [ ] #105
- [ ] #106
- [ ] #107
- [ ] #108
- [x] #109
- [x] #110
- [x] #111
- [ ] #112
- [ ] #113
- [ ] #114

**Comment by LoreBWolf** [comment]
Issue - [ ] geetz-app/geetz-frontend#377 adicionada a sprint

'' Ajustar largura de sliders de 4px para 2px ''

Assigned: @SaldanhaPrtt

**Comment by LoreBWolf** [comment]
Issue - [ ] geetz-app/geetz-backend#83 adicionada a sprint

'' Migrar banco de staging para RDS '' [^1].

Assigned: @jpadsbr1 

[^1]: Priority: Critical
Identificado que problema de staging estar caindo pode estar relacionado ao fato de não ter sido migrado para banco RDS como development, foi solicitado prioridade na implementação desta migração.

**Comment by LoreBWolf** [comment]
Issues adicionadas a sprint:

**🔗 Relates to**

- geetz-app/geetz-mobile#189

> [!IMPORTANT]
> Todos testes foram realizados em development.

**✨ Issues**

- [ ] #191
- [ ] #190
- [ ] #192
- [ ] #193
- [x] #195

**Comment by LoreBWolf** [comment]
Issues reabertas?

- [x] Stories retornando em ordem errada geetz-app/geetz-backend#21

> [!NOTE]
> Status: Failed QA testing - REOPENED
> Enviroment: Development
> Device: Samsung galaxy A54
> 
> Stories do mesmo usuário estão aparecendo em ordem errada, timestapms aparecem corretamente contudo a ordem em si de stories esta retornando de maneira aleatória


- [ ] Ajustar posição do like em UI de espectadores geetz-app/geetz-mobile#157

> [!NOTE]
> Status: Failed QA testing - REOPENED
> Enviroment: Development
> Device: Samsung galaxy A54
> 
> 1. UI de espectadores não possui variações de dark/lightmode
> 2. Ajustar proporção da tumbnail do story em UI de especadores, no momento parece estão mais comprida que proporções de 9:16
> 3. Ajustar posição do like em UI de espectadores para a direita do usuário, ao final da linha.

- [ ] Card de publicação tipo Snipz, cortando interações quando footer e header estão presentes geetz-app/geetz-mobile#140 

> [!NOTE]
> Status: Failed QA testing - REOPENED
> Enviroment: Development
> Device: Samsung galaxy A54
> 
> Card de snipz esta cortando parcialmente os ícones de interação quando o header e footer estão presentes. Card deve ser renderizado do inicio ao final dos icones de interação quando o header e footer estiverem expandidos.

- [ ] Foto tirada pela câmera aparece croppada em edição geetz-app/geetz-mobile#151 

> [!NOTE]
> Status: Failed QA testing - REOPENED
> Enviroment: Development
> Device: Samsung galaxy A54
> 
> Gravação de story pela câmera deve retornar imagem em 9:16 na edição, no momento esta retornando uma versão cropada incorretamente da imagem.
